resources:
- ../base/kube-prometheus/

configMapGenerator:
- name: kp-config
  namespace: monitoring
  behavior: merge
  literals:
  - DOMAIN=fraction.jp

images:
- name: grafana/grafana
  newTag: 7.5.11

secretGenerator:
- name: alertmanager-main
  namespace: monitoring
  behavior: merge
  files:
  - secrets/alertmanager.yaml
- name: basic-auth
  namespace: monitoring
  files:
  - secrets/auth

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: node-exporter
    namespace: monitoring
  spec:
    template:
      spec:
        containers:
        - name: node-exporter
          resources:
            limits:
              cpu: 500m
              memory: 180Mi
