---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ing
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/component: controller
  name: ing-ingress-nginx-controller-v6
  namespace: ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 2405:6581:8580:301:ace::200
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ing
    app.kubernetes.io/component: controller
