apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    'app.unstable.cloud': 'kubevirt'

resources:
- kubevirt
- cdi

patchesStrategicMerge:
- |-
  apiVersion: kubevirt.io/v1
  kind: KubeVirt
  metadata:
    name: kubevirt
    namespace: kubevirt
  spec:
    configuration:
      developerConfiguration:
        featureGates:
        - BlockVolume
