---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jammy
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      use: "jammy"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    vms: staging
    kubevirt.io/os: linux
  name: node
spec:
  running: true
  template:
    metadata:
      labels:
        vms: staging
    spec:
      subdomain: staging
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          # - disk:
          #     bus: virtio
          #   name: disk1
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          interfaces:
          - name: default
            bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 3Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - persistentVolumeClaim:
          claimName: jammy
        name: disk0
      # - persistentVolumeClaim:
      #     claimName: data
        # name: disk1
      - cloudInitNoCloud:
          secretRef:
            name: cloudinit
          networkDataSecretRef:
            name: cloudinit
        name: cloudinitdisk
