# Modify this file if you want to kustomize generated manifests
# This file will not be overridden by Porkadot.
labels:
- pairs:
    'kubernetes.unstable.cloud/installed-by': 'porkadot'
resources:
- manifests
# 
# patches:
# - patch: |-
#     apiVersion: apps/v1
#     kind: DaemonSet
#     metadata:
#       name: speaker
#       namespace: metallb-system
#     spec:
#       template:
#         spec:
#           nodeSelector:
#             metallb: speaker
