---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bedrock-connect
  name: proxy
spec:
  loadBalancerIP: 192.168.1.222
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
  - port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app: bedrock-connect
  sessionAffinity: None
  type: LoadBalancer
