resources:
- ../base/filestash/

patchesStrategicMerge:
- patches/deploy.yaml

configMapGenerator:
- name: fs-config
  namespace: filestash
  behavior: merge
  literals:
  - NFS_SERVER=192.168.1.121
  - FILESTASH_URL=files.fraction.jp

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: basic-auth
  namespace: filestash
  files:
  - secrets/auth
