---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: "minecraft"
  name: minecraft
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /export/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["oeilvert"]
