# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     use: "minecraft"
#   name: minecraft
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: "1Gi"
#   selector:
#     matchLabels:
#       use: "minecraft"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: "minecraft"
  name: minecraft
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/longhorn/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["chirico"]
