---
apiVersion: v1
kind: Service
metadata:
  name: bds-v4
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.223
  ipFamilies:
  - IPv4
  ports:
  - port: 19132
    protocol: UDP
    name: minecraft
