apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfslocal
parameters:
  compression: "off"
  dedup: "off"
  fstype: ext4
  poolname: tank
  recordsize: 4k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
