---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bds
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          use: "minecraft3"
