commonLabels:
  region: fraction
  app: proxy
namespace: proxy
resources:
- proxy.yaml
- code.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: basic-auth
  namespace: proxy
  files:
  - secrets/auth
