---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-copy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minecraft-copy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: minecraft-copy
    spec:
      containers:
      - image: ghcr.io/yuanying/docker-sshd:0.2.2
        imagePullPolicy: Always
        name: restore
        volumeMounts:
        - name: original
          mountPath: /var/original
        - name: dest
          mountPath: /var/dest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: original
        persistentVolumeClaim:
          claimName: data-bds-0
      - name: dest
        persistentVolumeClaim:
          claimName: minecraft
