commonLabels:
  region: fraction
resources:
- ../base/minecraft
- resources/svc.yaml

patchesStrategicMerge:
- patches/svc.yaml
- patches/cm.yaml
- patches/deploy.yaml

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: bds
  patch: |-
   - op: replace
     path: /spec/ports/0/port
     value: 19133

namespace: minecraft
