---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bds
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: bronze
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
