---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: "sites"
  name: sites
spec:
  capacity:
    storage: "10Gi"
  accessModes:
  - ReadWriteMany
  nfs:
    path: /sites
    server: sites.fs.svc.cluster.local
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    use: "sites"
  name: sites
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      use: "sites"
