---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.101/32
  - 192.168.1.190-192.168.1.254
  - 2405:6581:8580:301:ace::/96
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: system
  namespace: metallb-system

