apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    'app.unstable.cloud': 'minio'

namespace: minio

resources:
- ../base/minio
- ing.yaml

secretGenerator:
- name: minio
  files:
  - secrets/rootUser
  - secrets/rootPassword
