---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: metallb
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.101/32
      - 192.168.1.190-192.168.1.254
      - 2405:6581:8580:301:ace::/96


